spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.34.239:3306/sky_user?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    #验证连接的有效性
    test-while-idle: true
    #获取连接时候验证，会影响性能
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL


